### ISSUE TITLE
Milestone "Release 0.2" overview

### ISSUE THREAD

**Issue by AleksandarDev** [Sparkiy/sparkiy#1]
- [x] Sparkiy Language binding documentation
- [x] Sparkiy Engine binding documentation
- [x] Sparkiy Graphics binding documentation
- [x] Sparkiy Language binding API
- [x] Sparkiy Graphics binding API
- [x] Sparkiy C# Engine
- [x] Sparkiy Lua binding
- [x] Sparkiy DirectX binding
- [x] Sparkiy for Windows 8.1 ([Release 0.2](https://github.com/Sparkiy/sparkiy-client-w81/milestones/Release%200.2))
- [x] Sparkiy Web
  - [x] Sparkiy community [talk.sparkiy.com](http://talk.sparkiy.com)
  - [x] Sparkiy reference [reference.sparkiy.com](http://reference.sparkiy.com)
  - [x] Sparkiy development [dev.sparkiy.com](http://dev.sparkiy.com) and [sparkiy.github.io](http://sparkiy.github.io)
- [x] Write privacy statement https://github.com/Sparkiy/sparkiy-docs/issues/2
